
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AT = 37;
  public static final int IDENTIFIER = 97;
  public static final int LIMITED = 60;
  public static final int ARROW = 27;
  public static final int TYPE = 90;
  public static final int STARSTAR = 23;
  public static final int SUBTYPE = 85;
  public static final int RIGHT = 9;
  public static final int ALIASED = 33;
  public static final int LT_LT = 19;
  public static final int GE = 25;
  public static final int RAISE = 75;
  public static final int UNTIL = 91;
  public static final int RENAMES = 79;
  public static final int ELSIF = 48;
  public static final int TERMINATE = 88;
  public static final int COMMA = 13;
  public static final int ALL = 34;
  public static final int DECLARE = 42;
  public static final int ABORT = 28;
  public static final int ACCESS = 32;
  public static final int LOOP = 61;
  public static final int PROTECTED = 74;
  public static final int OUT = 69;
  public static final int NOT = 64;
  public static final int TASK = 87;
  public static final int ARRAY = 36;
  public static final int THEN = 89;
  public static final int GOTO = 56;
  public static final int PACKAGE = 70;
  public static final int RECORD = 77;
  public static final int REVERSE = 82;
  public static final int MOD = 62;
  public static final int WHEN = 93;
  public static final int GENERIC = 55;
  public static final int DIGITS = 45;
  public static final int SELECT = 83;
  public static final int OTHERS = 68;
  public static final int LESSTHAN = 3;
  public static final int ABSTRACT = 30;
  public static final int PIPE = 6;
  public static final int SLASH = 12;
  public static final int PLUS = 5;
  public static final int WHILE = 94;
  public static final int USE = 92;
  public static final int EQUAL = 16;
  public static final int ASSIGN = 26;
  public static final int CHARLIT = 98;
  public static final int DO = 46;
  public static final int FOR = 53;
  public static final int STAR = 8;
  public static final int GREATER = 14;
  public static final int RETURN = 81;
  public static final int DELAY = 43;
  public static final int ELSE = 47;
  public static final int DOTDOT = 18;
  public static final int DOT = 2;
  public static final int AMPERSAND = 7;
  public static final int PROCEDURE = 73;
  public static final int ENTRY = 50;
  public static final int PRAGMA = 71;
  public static final int DELTA = 44;
  public static final int NULL = 65;
  public static final int TICK = 17;
  public static final int BOX = 21;
  public static final int EOF = 0;
  public static final int SEMICOLON = 10;
  public static final int FUNCTION = 54;
  public static final int IS = 59;
  public static final int CONSTANT = 41;
  public static final int LEFTPARENTHESIS = 4;
  public static final int BODY = 39;
  public static final int ACCEPT = 31;
  public static final int IN = 58;
  public static final int OR = 67;
  public static final int error = 1;
  public static final int EXIT = 52;
  public static final int CHARSTRING = 99;
  public static final int IF = 57;
  public static final int OF = 66;
  public static final int ABS = 29;
  public static final int END = 49;
  public static final int REQUEUE = 80;
  public static final int REM = 78;
  public static final int COLON = 15;
  public static final int NUMERICLIT = 100;
  public static final int SEPARATE = 84;
  public static final int GT_GT = 20;
  public static final int BEGIN = 38;
  public static final int CASE = 40;
  public static final int EXCEPTION = 51;
  public static final int DASH = 11;
  public static final int NEW = 63;
  public static final int TAGGED = 86;
  public static final int RANGE = 76;
  public static final int AND = 35;
  public static final int PRIVATE = 72;
  public static final int WITH = 95;
  public static final int NE = 24;
  public static final int XOR = 96;
  public static final int LEQ = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "LESSTHAN",
  "LEFTPARENTHESIS",
  "PLUS",
  "PIPE",
  "AMPERSAND",
  "STAR",
  "RIGHT",
  "SEMICOLON",
  "DASH",
  "SLASH",
  "COMMA",
  "GREATER",
  "COLON",
  "EQUAL",
  "TICK",
  "DOTDOT",
  "LT_LT",
  "GT_GT",
  "BOX",
  "LEQ",
  "STARSTAR",
  "NE",
  "GE",
  "ASSIGN",
  "ARROW",
  "ABORT",
  "ABS",
  "ABSTRACT",
  "ACCEPT",
  "ACCESS",
  "ALIASED",
  "ALL",
  "AND",
  "ARRAY",
  "AT",
  "BEGIN",
  "BODY",
  "CASE",
  "CONSTANT",
  "DECLARE",
  "DELAY",
  "DELTA",
  "DIGITS",
  "DO",
  "ELSE",
  "ELSIF",
  "END",
  "ENTRY",
  "EXCEPTION",
  "EXIT",
  "FOR",
  "FUNCTION",
  "GENERIC",
  "GOTO",
  "IF",
  "IN",
  "IS",
  "LIMITED",
  "LOOP",
  "MOD",
  "NEW",
  "NOT",
  "NULL",
  "OF",
  "OR",
  "OTHERS",
  "OUT",
  "PACKAGE",
  "PRAGMA",
  "PRIVATE",
  "PROCEDURE",
  "PROTECTED",
  "RAISE",
  "RANGE",
  "RECORD",
  "REM",
  "RENAMES",
  "REQUEUE",
  "RETURN",
  "REVERSE",
  "SELECT",
  "SEPARATE",
  "SUBTYPE",
  "TAGGED",
  "TASK",
  "TERMINATE",
  "THEN",
  "TYPE",
  "UNTIL",
  "USE",
  "WHEN",
  "WHILE",
  "WITH",
  "XOR",
  "IDENTIFIER",
  "CHARLIT",
  "CHARSTRING",
  "NUMERICLIT"
  };
}

