
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AT = 35;
  public static final int REAL = 80;
  public static final int OPREL = 75;
  public static final int LIMITED = 63;
  public static final int TYPE = 32;
  public static final int SUBTYPE = 44;
  public static final int RAISE = 54;
  public static final int GET = 72;
  public static final int RENAMES = 43;
  public static final int ELSIF = 65;
  public static final int IDEN = 74;
  public static final int TERMINATE = 69;
  public static final int COMMA = 7;
  public static final int ALL = 58;
  public static final int INTEGER = 77;
  public static final int DECLARE = 36;
  public static final int ABORT = 9;
  public static final int PUT = 73;
  public static final int ACCESS = 46;
  public static final int LOOP = 15;
  public static final int OUT = 53;
  public static final int NOT = 52;
  public static final int TASK = 56;
  public static final int SUMSUBS = 2;
  public static final int ARRAY = 22;
  public static final int FLOAT = 78;
  public static final int THEN = 19;
  public static final int GOTO = 14;
  public static final int PACKAGE = 66;
  public static final int NUM = 79;
  public static final int RECORD = 17;
  public static final int REVERSE = 68;
  public static final int MOD = 27;
  public static final int WHEN = 57;
  public static final int GENERIC = 62;
  public static final int DIGITS = 12;
  public static final int SELECT = 18;
  public static final int OTHERS = 41;
  public static final int LPAR = 4;
  public static final int WHILE = 70;
  public static final int USE = 45;
  public static final int ASSIGN = 76;
  public static final int MULDIV = 3;
  public static final int BOOLEAN = 71;
  public static final int DO = 24;
  public static final int FOR = 38;
  public static final int RETURN = 55;
  public static final int DELAY = 48;
  public static final int ELSE = 37;
  public static final int DOTDOT = 8;
  public static final int PROCEDURE = 42;
  public static final int ENTRY = 61;
  public static final int DELTA = 60;
  public static final int NULL = 64;
  public static final int EOF = 0;
  public static final int SEMICOLON = 6;
  public static final int RPAR = 5;
  public static final int FUNCTION = 50;
  public static final int IS = 51;
  public static final int CONSTANT = 23;
  public static final int BODY = 59;
  public static final int ACCEPT = 34;
  public static final int IN = 39;
  public static final int OR = 28;
  public static final int error = 1;
  public static final int EXIT = 25;
  public static final int IF = 26;
  public static final int OF = 16;
  public static final int ABS = 21;
  public static final int END = 49;
  public static final int REM = 30;
  public static final int SEPARATE = 31;
  public static final int BEGIN = 47;
  public static final int CASE = 11;
  public static final int EXCEPTION = 13;
  public static final int NEW = 40;
  public static final int RANGE = 67;
  public static final int AND = 10;
  public static final int PRIVATE = 29;
  public static final int WITH = 20;
  public static final int XOR = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMSUBS",
  "MULDIV",
  "LPAR",
  "RPAR",
  "SEMICOLON",
  "COMMA",
  "DOTDOT",
  "ABORT",
  "AND",
  "CASE",
  "DIGITS",
  "EXCEPTION",
  "GOTO",
  "LOOP",
  "OF",
  "RECORD",
  "SELECT",
  "THEN",
  "WITH",
  "ABS",
  "ARRAY",
  "CONSTANT",
  "DO",
  "EXIT",
  "IF",
  "MOD",
  "OR",
  "PRIVATE",
  "REM",
  "SEPARATE",
  "TYPE",
  "XOR",
  "ACCEPT",
  "AT",
  "DECLARE",
  "ELSE",
  "FOR",
  "IN",
  "NEW",
  "OTHERS",
  "PROCEDURE",
  "RENAMES",
  "SUBTYPE",
  "USE",
  "ACCESS",
  "BEGIN",
  "DELAY",
  "END",
  "FUNCTION",
  "IS",
  "NOT",
  "OUT",
  "RAISE",
  "RETURN",
  "TASK",
  "WHEN",
  "ALL",
  "BODY",
  "DELTA",
  "ENTRY",
  "GENERIC",
  "LIMITED",
  "NULL",
  "ELSIF",
  "PACKAGE",
  "RANGE",
  "REVERSE",
  "TERMINATE",
  "WHILE",
  "BOOLEAN",
  "GET",
  "PUT",
  "IDEN",
  "OPREL",
  "ASSIGN",
  "INTEGER",
  "FLOAT",
  "NUM",
  "REAL"
  };
}

